dftr1 = input("Masukkan daftar belanja 1: ")
dftr2 = input("Masukkan daftar belanja 2: ")
tmbh1= input("Tambahkan data ke daftar belanja 1: ")
tmbh2 = input("Tambahkan data ke daftar belanja 2: ")
print("Daftar belanja 1 adalah "+dftr1+","+tmbh1)
print("Daftar belanja 2 adalah "+dftr2+","+tmbh2)